services:

  # Tcpdump host that stores all the stuff that happens
  # in the network
  tcpdump:
    image: kaazing/tcpdump
    network_mode: "host"
    volumes:
        - ../tcpdump:/tcpdump
    # Run tcdump in autorotating mode, with gzip compression
    # The files will be rotated every 24h or 500MB and named
    # after the timestamp when the file is created.
    command: [
      "-z", "gzip", # compress to gzip
      "-G", "86400", # 24h in seconds
      "-C", "500", # maximum file size
      "-W", "10", # ignored, only affects the name
      "-v", # verbose
      "-i", "any", # any interface
      "-w", "tcpdump/trace_%Y_%m_%d_%H_%M_%S.pcap" # trace_<timestamp>.pcap
    ]

  # RIoTPot is the container for the central node
  riotpot:
    build:
      context: ..
      dockerfile: ./build/docker/Dockerfile
    image: riotpot
    restart: always
    ports:
      # Ports under 60 might see errors when unquoted
      # https://stackoverflow.com/questions/58810789/quotes-on-docker-compose-yml-ports-make-any-difference
      - "7:7"
      - "22:22"
      - "23:23"
      - "80:80"
      - "502:502"
      - "1883:1883"
      - "5683:5683"
    env_file:
    - ../build/env/.env

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    volumes:
      - postgres_data:/var/lib/postgresql/data/


  # This will create a Tor proxy server to our service
  # running in port `80` and `8080`.
  # NOTE: the httpd plugin runs on port 80
  tor:
    image: goldy/tor-hidden-service
    links:
      - riotpot
    environment:
      RIOTPOT_TOR_SERVICE_HOSTS: '80:riotpot:80,8080:riotpot:8080'
      RIOTPOT_TOR_SERVICE_VERSION: '3'

    volumes:
      - tor-keys:/var/lib/tor/hidden_service/

    secrets:
      - riotpot

volumes:
  postgres_data:
  tor-keys:

secrets:
  riotpot:
    # NOTE: Tor v3 addresses uses ed25519 binary keys.
    file: ../configs/keys/private_key_tor