/:
  get:
    operationId: getServices
    description: Get all the registered services
    tags:
      - Services
    responses:
      "200":
        description: Returns all the proxies
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: Service.yaml
  post:
    operationId: createService
    summary: Create a new Service
    tags:
      - Services
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                $ref: Service.yaml#/properties/name
              port:
                $ref: Px.yaml#/properties/port
              network:
                $ref: Px.yaml#/properties/network
              host:
                $ref: Service.yaml#/properties/host
              interaction:
                $ref: Service.yaml#/properties/interaction
    responses:
      "200":
        description: Returns the structure of the proxy created
        content:
          application/json:
            schema:
              $ref: Service.yaml

/new:
  post:
    operationId: newService
    summary: Create a new Service and Proxy
    tags:
      - Services
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                $ref: Service.yaml#/properties/name
              port:
                $ref: Px.yaml#/properties/port
              network:
                $ref: Px.yaml#/properties/network
              host:
                $ref: Service.yaml#/properties/host
              interaction:
                $ref: Service.yaml#/properties/interaction
    responses:
      "200":
        description: Returns the structure of a new proxy and the service
        content:
          application/json:
            schema:
              $ref: Proxy.yaml

/{id}:
  parameters:
    - name: id
      in: path
      required: true
      schema:
        $ref: Px.yaml#/properties/id

  get:
    operationId: getService
    description: Get an instance of a registered service
    tags:
      - Services
    parameters:
      - name: id
        in: path
        required: true
        schema:
          $ref: Px.yaml#/properties/id
    responses:
      "200":
        description: Returns the instance of the service
        content:
          application/json:
            schema:
              $ref: Service.yaml

  patch:
    operationId: updateService
    description: Updates a service with new values
    tags:
      - Services
    parameters:
      - name: id
        in: path
        required: true
        schema:
          $ref: Px.yaml#/properties/id
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                $ref: Service.yaml#/properties/name
              port:
                $ref: Px.yaml#/properties/port
              host:
                $ref: Service.yaml#/properties/host
    responses:
      "200":
        description: Returns the instance of the proxy updated
        content:
          application/json:
            schema:
              $ref: Service.yaml
  delete:
    operationId: deleteService
    description: Removes a service
    tags:
      - Services
    parameters:
      - name: id
        in: path
        required: true
        schema:
          $ref: Px.yaml#/properties/id
    responses:
      "200":
        description: OK
